//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.3.0+a325ba3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>RichTextSettings</summary>
	[PublishedModel("richTextSettings")]
	public partial class RichTextSettings : PublishedElementModel, IAlignmentSettings, IColorSettings, IGapSettings, IVisibilitySettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		public new const string ModelTypeAlias = "richTextSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<RichTextSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public RichTextSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Vertikale Ausrichtung
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("verticalAlignment")]
		public virtual string VerticalAlignment => global::Umbraco.Cms.Web.Common.PublishedModels.AlignmentSettings.GetVerticalAlignment(this, _publishedValueFallback);

		///<summary>
		/// Background-Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColor")]
		public virtual string BackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.ColorSettings.GetBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.ColorSettings.GetBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Unten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("mb")]
		public virtual decimal Mb => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMb(this, _publishedValueFallback);

		///<summary>
		/// Unten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("mbMD")]
		public virtual decimal MbMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMbMD(this, _publishedValueFallback);

		///<summary>
		/// Unten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("mbSM")]
		public virtual decimal MbSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMbSM(this, _publishedValueFallback);

		///<summary>
		/// Rechts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("me")]
		public virtual decimal Me => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMe(this, _publishedValueFallback);

		///<summary>
		/// Rechts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("meMD")]
		public virtual decimal MeMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMeMD(this, _publishedValueFallback);

		///<summary>
		/// Rechts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("meSM")]
		public virtual decimal MeSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMeSM(this, _publishedValueFallback);

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("ms")]
		public virtual decimal Ms => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMs(this, _publishedValueFallback);

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("msMD")]
		public virtual decimal MsMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMsMD(this, _publishedValueFallback);

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("msSM")]
		public virtual decimal MsSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMsSM(this, _publishedValueFallback);

		///<summary>
		/// Oben
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("mt")]
		public virtual decimal Mt => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMt(this, _publishedValueFallback);

		///<summary>
		/// Oben
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("mtMD")]
		public virtual decimal MtMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMtMD(this, _publishedValueFallback);

		///<summary>
		/// Oben
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("mtSM")]
		public virtual decimal MtSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetMtSM(this, _publishedValueFallback);

		///<summary>
		/// Unten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("pb")]
		public virtual decimal Pb => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPb(this, _publishedValueFallback);

		///<summary>
		/// Unten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("pbMD")]
		public virtual decimal PbMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPbMD(this, _publishedValueFallback);

		///<summary>
		/// Unten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("pbSM")]
		public virtual decimal PbSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPbSM(this, _publishedValueFallback);

		///<summary>
		/// Rechts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("pe")]
		public virtual decimal Pe => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPe(this, _publishedValueFallback);

		///<summary>
		/// Rechts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("peMD")]
		public virtual decimal PeMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPeMD(this, _publishedValueFallback);

		///<summary>
		/// Rechts
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("peSM")]
		public virtual decimal PeSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPeSM(this, _publishedValueFallback);

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("ps")]
		public virtual decimal Ps => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPs(this, _publishedValueFallback);

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("psMD")]
		public virtual decimal PsMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPsMD(this, _publishedValueFallback);

		///<summary>
		/// Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("psSM")]
		public virtual decimal PsSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPsSM(this, _publishedValueFallback);

		///<summary>
		/// Oben
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("pt")]
		public virtual decimal Pt => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPt(this, _publishedValueFallback);

		///<summary>
		/// Oben
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("ptMD")]
		public virtual decimal PtMD => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPtMD(this, _publishedValueFallback);

		///<summary>
		/// Oben
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("ptSM")]
		public virtual decimal PtSM => global::Umbraco.Cms.Web.Common.PublishedModels.GapSettings.GetPtSM(this, _publishedValueFallback);

		///<summary>
		/// Desktop: Legt fest ob das Element bei einer Auflösung von größer **≥992px** sichtbar ist.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("visibilityDesktop")]
		public virtual bool VisibilityDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.VisibilitySettings.GetVisibilityDesktop(this, _publishedValueFallback);

		///<summary>
		/// Mobile: Legt fest ob das Element bei einer Auflösung von kleiner**{768px** sichtbar ist.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("visibilityMobile")]
		public virtual bool VisibilityMobile => global::Umbraco.Cms.Web.Common.PublishedModels.VisibilitySettings.GetVisibilityMobile(this, _publishedValueFallback);

		///<summary>
		/// Tablet: Legt fest ob das Element bei einer Auflösung von größer **≥ 768px** und **{ 992px** sichtbar ist.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("visibilityTablet")]
		public virtual bool VisibilityTablet => global::Umbraco.Cms.Web.Common.PublishedModels.VisibilitySettings.GetVisibilityTablet(this, _publishedValueFallback);
	}
}
