//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.3.0+a325ba3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Einzel</summary>
	[PublishedModel("singleDataSet")]
	public partial class SingleDataSet : PublishedElementModel, IAuditDataSet
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		public new const string ModelTypeAlias = "singleDataSet";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<SingleDataSet, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SingleDataSet(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// zur Prüfung zugelassen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("admitted")]
		public virtual int Admitted => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetAdmitted(this, _publishedValueFallback);

		///<summary>
		/// zur Prüfung erschienen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("appeared")]
		public virtual int Appeared => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetAppeared(this, _publishedValueFallback);

		///<summary>
		/// Zulassungsanträge
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("applications")]
		public virtual int Applications => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetApplications(this, _publishedValueFallback);

		///<summary>
		/// Steuerberaterkammer bzw. Bundesland
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("auditName")]
		public virtual string AuditName => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetAuditName(this, _publishedValueFallback);

		///<summary>
		/// Entry Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("entryId")]
		public virtual string EntryId => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetEntryId(this, _publishedValueFallback);

		///<summary>
		/// entschuldigt an mP nicht teilgenommen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("excusedMp")]
		public virtual int ExcusedMp => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetExcusedMp(this, _publishedValueFallback);

		///<summary>
		/// sP nicht bestanden in v. H.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("failedFromHundred")]
		public virtual decimal FailedFromHundred => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetFailedFromHundred(this, _publishedValueFallback);

		///<summary>
		/// zu mündlicher Prüfung (mp) geladen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("invitedToMp")]
		public virtual int InvitedToMp => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetInvitedToMp(this, _publishedValueFallback);

		///<summary>
		/// sP nicht bestanden
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("notPassed")]
		public virtual int NotPassed => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetNotPassed(this, _publishedValueFallback);

		///<summary>
		/// Insgesamt bestanden
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("overallPassed")]
		public virtual int OverallPassed => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetOverallPassed(this, _publishedValueFallback);

		///<summary>
		/// Insgesamt bestanden in v. H.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("overallPassedFromHundert")]
		public virtual decimal OverallPassedFromHundert => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetOverallPassedFromHundert(this, _publishedValueFallback);

		///<summary>
		/// vor der Prüfung zurückgetreten
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("resignedBefore")]
		public virtual int ResignedBefore => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetResignedBefore(this, _publishedValueFallback);

		///<summary>
		/// Rücktritt während der Prüfung
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("withdrawalDuring")]
		public virtual int WithdrawalDuring => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetWithdrawalDuring(this, _publishedValueFallback);

		///<summary>
		/// schriftliche Prüfung (sP) abgelegt (=100)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.3.0+a325ba3")]
		[ImplementPropertyType("writtenExamination")]
		public virtual int WrittenExamination => global::Umbraco.Cms.Web.Common.PublishedModels.AuditDataSet.GetWrittenExamination(this, _publishedValueFallback);
	}
}
